---
title: "Currículo - Cleto Ribas"
format: html
engine: knitr
---
  
# Cleto Ribas  
**Marketplace Manager**  
Curitiba, Paraná, Brazil  
Email: cleto.diogo1@gmail.com  
Phone: +55 41 99601-4088

## Resumo Profissional
Marketplace Manager com vasta experiência em desenvolvimento de projetos de web scraping, crawlers, soluções baseadas em APIs, análise de dados, geração de leads e gerenciamento de bancos de dados em nuvem. Habilidades em Python, SQL, Power BI e ferramentas de IA para otimizar processos e impulsionar o crescimento empresarial.

## Competências Principais
- **Programação**: Python, APIs
- **Análise de Dados & Visualização**: SQL, Power BI
- **Geração de Leads & Otimização do Funil de Vendas**: Ferramentas de IA
- **Gestão de Bancos de Dados na Nuvem**: AWS Athena
- **Inteligência de Negócios & Relatórios**: KPIs, insights acionáveis
- **Gestão de Suprimentos & Inventário**: Negociação com fornecedores, controle de estoque

## Experiência Profissional

### Tudo para Moto
**Marketplace Manager**  
*Julho 2024 - Presente (8 meses) | Paraná, Brasil*  
- Desenvolvimento e otimização de crawlers, scripts de web scraping e integrações de APIs para coleta de dados.
- Análise de dados e desenvolvimento de KPIs para impulsionar o crescimento e tomar decisões estratégicas.

### Olist
**Commercial Intelligence Analyst**  
*Janeiro 2024 - Julho 2024 (7 meses) | Curitiba, Paraná, Brasil*  
- Análise de dados e geração de soluções de inteligência comercial para a melhoria da performance de vendas.
- Otimização de processos de geração de leads e qualidade do funil de vendas.

### Geo Biogas & Tech
**Data Analytics Intern**  
*Outubro 2022 - Janeiro 2024 (1 ano e 4 meses) | Curitiba, Paraná, Brasil*  
- Análise de grandes volumes de dados para gerar insights para otimização de negócios e processos internos.
- Contribuição no design de soluções baseadas em IA para análise e tomada de decisões.

### Fibracem Teleinformática
**Materials Planning and Control Intern**  
*Novembro 2021 - Outubro 2022 (1 ano) | Pinhais, Paraná, Brasil*  
- Suporte no controle de estoque e negociação com fornecedores para compras e prazos de entrega.
- Acompanhamento das operações fiscais ligadas ao processo de vendas.

## Formação Acadêmica

**FAE Centro Universitário**  
*Bacharelado em Data Science for Business*  
*Janeiro 2024 - Dezembro 2027*  

**Universidade Tecnológica Federal do Paraná**  
*Bacharelado em Engenharia Mecatrônica, Robótica e Automação*  
*2016 - 2023*

## Idiomas
- **Inglês**: Avançado

## Contato
- Email: [cleto.diogo1@gmail.com](mailto:cleto.diogo1@gmail.com)
- Phone: +55 41 99601-4088
